
ALTER TABLE public.leo_conversations
  ADD COLUMN IF NOT EXISTS largura NUMERIC,
  ADD COLUMN IF NOT EXISTS altura NUMERIC,
  ADD COLUMN IF NOT EXISTS tipo_perfil TEXT,
  ADD COLUMN IF NOT EXISTS cep TEXT,
  ADD COLUMN IF NOT EXISTS frete NUMERIC,
  ADD COLUMN IF NOT EXISTS endereco_instalacao TEXT;
